repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 26.5.1
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 9.0.0a3
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.2
  hooks:
    - id: check-github-workflows
